spring:
  profiles:
    active: dev
  application:
    name: springai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen3:4b
    openai:
#      api-key: sk-bbf1879d3cae4103bb1c2e75047e98bf
      api-key: ${springAI.openai.api-key}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
#      base-url: https://api.deepseek.com
      chat:
        options:
          model: qwen3-next-80b-a3b-instruct
          extra-body:
            enable_thinking: true
        memory:
          repository:
            jdbc:
              initialize-schema: always # 自动建表
              schema: classpath:sql/chatHistory.sql # 建表脚本
      embedding:
        options:
          model: text-embedding-v3
          dimensions: 1024


  datasource:
    url: jdbc:mysql://localhost:3306/spring_ai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

#logging:
#  level:
#    org.springframework.ai: debug
#    com.main.springai: debug

logging:
  level:
    org.springframework.ai: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.main.demo.entity

